apiVersion: v1
kind: Endpoints
metadata:
    name: madome-file
subsets:
    - addresses:
          - ip: 127.0.0.1
      ports:
          - port: 5433
---
apiVersion: v1
kind: Service
metadata:
    name: madome-file
spec:
    ports:
        - port: 5432
          targetPort: 5433
